// src/config/premiumConfig.js
export const PLANS = {
  free: {
    id: 'free',
    name: 'Free',
    icon: '🆓',
    color: '#6B7280',
    maxGroups: 3,
    maxMembersPerGroup: 6,
    maxExpensesPerMonth: 50,
    maxExpensesPerGroup: 6,       // ← ADD THIS
    features: {
      equalSplit: true,
      unequalSplit: false,
      percentageSplit: false,
      sharesSplit: false,
      groupChat: true,
      maxChatMessages: 100,
      settlementRequests: true,
      paymentProof: false,
      expenseCategories: false,
      recurringExpenses: false,
      exportCSV: false,
      analytics: false,
      debtReminders: 3,
      customGroupIcons: false,
      receiptScanning: false,
      multiCurrency: false,
      darkMode: false,
      prioritySupport: false,
      adFree: false,
      expenseReactions: false,
      expenseNotes: false,
      budgetLimits: false,
    },
  },
  pro: {
    id: 'pro',
    name: 'Pro',
    icon: '⭐',
    color: '#6366F1',
    maxGroups: 25,
    maxMembersPerGroup: 30,
    maxExpensesPerMonth: 500,
    maxExpensesPerGroup: -1,       // ← UNLIMITED
    features: {
      equalSplit: true,
      unequalSplit: true,
      percentageSplit: true,
      sharesSplit: true,
      groupChat: true,
      maxChatMessages: -1,
      settlementRequests: true,
      paymentProof: true,
      expenseCategories: true,
      recurringExpenses: true,
      exportCSV: true,
      analytics: true,
      debtReminders: -1,
      customGroupIcons: true,
      receiptScanning: false,
      multiCurrency: true,
      darkMode: true,
      prioritySupport: false,
      adFree: true,
      expenseReactions: true,
      expenseNotes: true,
      budgetLimits: true,
    },
    pricing: {
      monthly: { INR: 149, USD: 1.99, label: '₹149/mo' },
      yearly: { INR: 999, USD: 14.99, label: '₹999/yr', savings: '44%' },
    },
  },
  premium: {
    id: 'premium',
    name: 'Premium',
    icon: '💎',
    color: '#F59E0B',
    maxGroups: -1,
    maxMembersPerGroup: -1,
    maxExpensesPerMonth: -1,
    maxExpensesPerGroup: -1,       // ← UNLIMITED
    features: {
      equalSplit: true,
      unequalSplit: true,
      percentageSplit: true,
      sharesSplit: true,
      groupChat: true,
      maxChatMessages: -1,
      settlementRequests: true,
      paymentProof: true,
      expenseCategories: true,
      recurringExpenses: true,
      exportCSV: true,
      analytics: true,
      debtReminders: -1,
      customGroupIcons: true,
      receiptScanning: true,
      multiCurrency: true,
      darkMode: true,
      prioritySupport: true,
      adFree: true,
      expenseReactions: true,
      expenseNotes: true,
      budgetLimits: true,
    },
    pricing: {
      monthly: { INR: 249, USD: 2.99, label: '₹249/mo' },
      yearly: { INR: 1499, USD: 19.99, label: '₹1499/yr', savings: '50%' },
      lifetime: { INR: 2499, USD: 29.99, label: '₹2499 once', savings: 'Pay once, use forever' },
    },
  },
};

// Add maxExpensesPerGroup to PREMIUM_FEATURES for display on paywall
export const PREMIUM_FEATURES = [
  {
    key: 'maxExpensesPerGroup',                              // ← ADD THIS
    title: 'Unlimited Expenses per Group',
    desc: 'Add as many expenses as you need in each group',
    icon: 'receipt',
    freeLimit: '6 per group',
    proValue: 'Unlimited',
  },
  {
    key: 'unequalSplit',
    title: 'Unequal Splits',
    desc: 'Split by percentage, exact amounts, or share ratios',
    icon: 'pie-chart',
    freeLimit: 'Equal only',
    proValue: '✓ All methods',
  },
  {
    key: 'analytics',
    title: 'Analytics Dashboard',
    desc: 'Spending insights, category breakdown, trends',
    icon: 'bar-chart',
    freeLimit: '✗',
    proValue: '✓ Full dashboard',
  },
  {
    key: 'exportCSV',
    title: 'Export Reports',
    desc: 'Download CSV reports of all expenses',
    icon: 'download',
    freeLimit: '✗',
    proValue: '✓ Unlimited exports',
  },
  {
    key: 'paymentProof',
    title: 'Payment Proof',
    desc: 'Attach photos as proof of payment',
    icon: 'camera',
    freeLimit: '✗',
    proValue: '✓ With cloud storage',
  },
  {
    key: 'recurringExpenses',
    title: 'Recurring Expenses',
    desc: 'Auto-add rent, subscriptions, etc.',
    icon: 'repeat',
    freeLimit: '✗',
    proValue: '✓ Daily/Weekly/Monthly',
  },
  {
    key: 'expenseCategories',
    title: 'Smart Categories',
    desc: 'Auto-detect expense categories',
    icon: 'pricetags',
    freeLimit: '✗',
    proValue: '✓ 12+ categories',
  },
  {
    key: 'maxGroups',
    title: 'Unlimited Groups',
    desc: 'Create as many groups as you need',
    icon: 'people',
    freeLimit: '3 groups',
    proValue: '25 groups',
    premiumValue: 'Unlimited',
  },
  {
    key: 'debtReminders',
    title: 'Unlimited Reminders',
    desc: 'Send payment reminders to friends',
    icon: 'notifications',
    freeLimit: '3/month',
    proValue: 'Unlimited',
  },
  {
    key: 'adFree',
    title: 'Ad-Free Experience',
    desc: 'No banners, no interruptions',
    icon: 'eye-off',
    freeLimit: 'With ads',
    proValue: 'No ads',
  },
  {
    key: 'budgetLimits',
    title: 'Budget Limits',
    desc: 'Set spending limits per group or category',
    icon: 'shield-checkmark',
    freeLimit: '✗',
    proValue: '✓',
  },
];