// src/config/premiumConfig.js
export const PLANS = {
  free: {
    id: 'free',
    name: 'Free',
    icon: '🆓',
    color: '#6B7280',
    maxGroups: 2,
    maxMembersPerGroup: 4,
    maxExpensesPerMonth: 15,
    maxExpensesPerGroup: 3,
    features: {
      equalSplit: true,
      advancedSplits: false,
      groupChat: false,
      maxChatMessages: 0,
      settlementRequests: true,
      paymentProof: false,
      expenseCategories: false,
      recurringExpenses: false,
      exportCSV: false,
      analytics: false,
      debtReminders: 1,
      customGroupIcons: false,
      receiptScanning: false,
      multiCurrency: false,
      darkMode: false,
      prioritySupport: false,
      adFree: false,
      expenseReactions: false,
      expenseNotes: false,
      budgetLimits: false,
    },
  },
  premium: {
    id: 'premium',
    name: 'Premium',
    icon: '💎',
    color: '#F59E0B',
    maxGroups: -1,
    maxMembersPerGroup: -1,
    maxExpensesPerMonth: -1,
    maxExpensesPerGroup: -1,
    features: {
      equalSplit: true,
      advancedSplits: true,
      groupChat: true,
      maxChatMessages: -1,
      settlementRequests: true,
      paymentProof: true,
      expenseCategories: true,
      recurringExpenses: true,
      exportCSV: true,
      analytics: true,
      debtReminders: -1,
      customGroupIcons: true,
      receiptScanning: true,
      multiCurrency: true,
      darkMode: true,
      prioritySupport: true,
      adFree: true,
      expenseReactions: true,
      expenseNotes: true,
      budgetLimits: true,
    },
    pricing: {
      lifetime: {
        INR: 149,
        USD: 1.99,
        label: '₹149 Forever',
        savings: 'Lifetime Access • No Renewals',
      },
    },
  },
};

export const PREMIUM_FEATURES = [
  {
    key: 'maxExpensesPerGroup',
    title: 'Unlimited Expenses',
    desc: 'Add as many expenses as you need in each group',
    icon: 'receipt',
    freeLimit: '3 per group',
    premiumValue: 'Unlimited',
  },
  {
    key: 'maxGroups',
    title: 'Unlimited Groups',
    desc: 'Create as many groups as you want',
    icon: 'people',
    freeLimit: '2 groups',
    premiumValue: 'Unlimited',
  },
  {
    key: 'advancedSplits',
    title: 'Advanced Split Methods',
    desc: 'Split by percentage, exact amounts, or share ratios',
    icon: 'pie-chart',
    freeLimit: 'Equal only',
    premiumValue: 'All methods',
  },
  {
    key: 'groupChat',
    title: 'Group Chat',
    desc: 'Discuss expenses and coordinate with your group',
    icon: 'chatbubbles',
    freeLimit: '✗',
    premiumValue: '✓',
  },
  {
    key: 'receiptScanning',
    title: 'Receipt Scanning',
    desc: 'Scan receipts with AI to auto-fill expenses',
    icon: 'scan',
    freeLimit: '✗',
    premiumValue: '✓',
  },
  {
    key: 'analytics',
    title: 'Analytics Dashboard',
    desc: 'Spending insights, category breakdown, and trends',
    icon: 'bar-chart',
    freeLimit: '✗',
    premiumValue: '✓',
  },
  {
    key: 'exportCSV',
    title: 'Export Reports',
    desc: 'Download CSV/PDF reports of all expenses',
    icon: 'download',
    freeLimit: '✗',
    premiumValue: '✓',
  },
  {
    key: 'paymentProof',
    title: 'Payment Proof',
    desc: 'Attach photos as proof of payment',
    icon: 'camera',
    freeLimit: '✗',
    premiumValue: '✓',
  },
  {
    key: 'recurringExpenses',
    title: 'Recurring Expenses',
    desc: 'Auto-add rent, subscriptions, bills',
    icon: 'repeat',
    freeLimit: '✗',
    premiumValue: '✓',
  },
  {
    key: 'debtReminders',
    title: 'Unlimited Reminders',
    desc: 'Send payment reminders to friends',
    icon: 'notifications',
    freeLimit: '1/month',
    premiumValue: 'Unlimited',
  },
  {
    key: 'adFree',
    title: 'Ad-Free Experience',
    desc: 'No banners, no interruptions',
    icon: 'eye-off',
    freeLimit: 'With ads',
    premiumValue: 'No ads',
  },
  {
    key: 'multiCurrency',
    title: 'Multi-Currency Support',
    desc: 'Track expenses in different currencies',
    icon: 'cash',
    freeLimit: '✗',
    premiumValue: '✓',
  },
];